# Generated by Django 3.2.8 on 2021-10-31 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20211031_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('discount', models.IntegerField(default='0', verbose_name='درصد تخفیف')),
                ('status', models.CharField(choices=[('تکمیل شده', 'تکمیل شده'), ('لغو شده', 'لغو شده'), ('دریافت پیش پرداخت', 'دریافت پیش پرداخت'), ('پرداخت شده', 'پرداخت شده'), ('در حال بررسی', 'در حال بررسی')], default='در حال بررسی', max_length=30, verbose_name='وضعیت')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer', verbose_name='خریدار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.AlterField(
            model_name='order_steps',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order_request', verbose_name='برای سفارش'),
        ),
        migrations.DeleteModel(
            name='Order_req',
        ),
    ]
