# Generated by Django 3.2.8 on 2021-10-31 20:07

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_request_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='order_request',
            name='date_created',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='order_steps',
            name='date_created',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=200, verbose_name='قیمت ( ریال )'),
        ),
    ]
