# Generated by Django 3.2.8 on 2021-11-01 13:18

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211031_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=400, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(max_length=200, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='customer',
            name='substantial',
            field=models.BooleanField(default=False, verbose_name=' قابل توجه '),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default='1', verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='order_request',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='order_request',
            name='status',
            field=models.CharField(choices=[('تکمیل شده', 'تکمیل شده'), ('لغو شده', 'لغو شده'), ('دریافت پیش پرداخت', 'دریافت پیش پرداخت'), ('در حال بررسی', 'در حال بررسی')], default='در حال بررسی', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order_steps',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/Default.png', upload_to='media', verbose_name='تصویر'),
        ),
    ]
