# Generated by Django 3.2.8 on 2021-11-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211101_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_request',
            name='status',
            field=models.CharField(choices=[('تکمیل شده', 'تکمیل شده'), ('لغو شده', 'لغو شده'), ('دریافت پیش پرداخت', 'دریافت پیش پرداخت'), ('در حال بررسی', 'در حال بررسی'), ('جدید', 'جدید')], default='در حال بررسی', max_length=30, verbose_name='وضعیت'),
        ),
    ]
