# Generated by Django 3.2.8 on 2021-11-02 20:05

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_order_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_incomings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='قیمت ( ریال )')),
                ('date_created', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'مبلغ ورودی سفارش',
                'verbose_name_plural': 'مبالغ ورودی سفارش',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='substantial',
            field=models.BooleanField(default=False, verbose_name='مشتری ویژه'),
        ),
        migrations.AlterField(
            model_name='order_request',
            name='status',
            field=models.CharField(choices=[('تکمیل شده', 'تکمیل شده'), ('لغو شده', 'لغو شده'), ('دریافت پیش پرداخت', 'دریافت پیش پرداخت'), ('در حال بررسی', 'در حال بررسی'), ('جدید', 'جدید')], default='جدید', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت ( ریال )'),
        ),
        migrations.DeleteModel(
            name='Order_steps',
        ),
        migrations.AddField(
            model_name='order_incomings',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order_request', verbose_name='برای سفارش'),
        ),
    ]
