# Generated by Django 3.2.8 on 2021-11-02 22:14

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211102_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_incomings',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
    ]
