# Generated by Django 3.2.8 on 2021-11-09 14:14

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_request',
            name='date_updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
    ]
