# Generated by Django 3.2.9 on 2021-11-17 14:49

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_order_request_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_request',
            name='date_updated',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
    ]
