# Generated by Django 3.2.9 on 2021-11-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_order_request_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_request',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
    ]
