# Generated by Django 3.2.9 on 2021-11-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_order_request_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_request',
            old_name='date_updated',
            new_name='updated',
        ),
    ]
