# Generated by Django 3.2.9 on 2021-11-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_date_updated_order_request_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_request',
            name='updated',
        ),
        migrations.AddField(
            model_name='order_request',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
    ]
