# Generated by Django 3.2.9 on 2021-11-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211117_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_request',
            name='date_updated',
        ),
    ]
